/* pack-images.js — packs converted AI art (<name>-grid.json emitted by
   tools/sprite-import.py) into src/25-images.js as an RLE image registry.

   Format: IMG['name'] = { w, h, pal: ['#rrggbb', ...], d: '<pairs>' }
   d is pairs of base62 chars: [colorIndex][runLen-1]; colorIndex 0 =
   transparent, 1..N = pal[index-1]; runs longer than 62 are split.
   Charset is alphanumeric only — safe inside a <script> (no '<', '/', '`').

   Usage: node tools/pack-images.js  (reads ~/Desktop/dd_character_art) */
const fs = require('fs');
const path = require('path');
const os = require('os');

const ART = path.join(os.homedir(), 'Desktop', 'dd_character_art');
const OUT = path.join(__dirname, '..', 'src', '25-images.js');
const B62 = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';

function packOne(grid, legend) {
  // build palette: legend chars -> colors; '.' = transparent
  const pal = [];
  const idxOf = { '.': 0 };
  for (const key of Object.keys(legend)) {
    pal.push(legend[key]);
    idxOf[key] = pal.length; // 1-based
  }
  if (pal.length > 61) throw new Error('palette too large: ' + pal.length);
  let d = '';
  let run = null; // [colorIdx, len]
  const flush = () => {
    if (!run) return;
    let [ci, len] = run;
    while (len > 0) {
      const take = Math.min(62, len);
      d += B62[ci] + B62[take - 1];
      len -= take;
    }
    run = null;
  };
  for (const row of grid) {
    for (const ch of row) {
      const ci = idxOf[ch] !== undefined ? idxOf[ch] : 0;
      if (run && run[0] === ci) run[1]++;
      else { flush(); run = [ci, 1]; }
    }
    flush(); // runs never cross row boundaries (keeps decode simple)
  }
  return { pal, d, w: grid[0].length, h: grid.length };
}

function main() {
  const files = fs.readdirSync(ART).filter(f => f.endsWith('-grid.json')).sort();
  let js = '/* 25-images.js — GENERATED by tools/pack-images.js. Do not hand-edit.\n';
  js += '   AI-generated art (gpt-image-1) converted to GBA sprites and RLE-packed. */\n';
  js += 'var IMG = {};\n';
  let total = 0;
  for (const f of files) {
    const name = f.replace('-grid.json', '');
    const j = JSON.parse(fs.readFileSync(path.join(ART, f), 'utf8'));
    const p = packOne(j.grid, j.legend);
    if (p.d.indexOf('<') >= 0) throw new Error('unsafe char in ' + name);
    js += "IMG['" + name + "']={w:" + p.w + ',h:' + p.h + ",pal:" + JSON.stringify(p.pal) + ",d:'" + p.d + "'};\n";
    total += p.d.length;
    console.log('  packed ' + name + ' ' + p.w + 'x' + p.h + ' pal=' + p.pal.length + ' rle=' + p.d.length);
  }
  fs.writeFileSync(OUT, js);
  console.log('wrote src/25-images.js — ' + files.length + ' images, ' + (js.length / 1024).toFixed(1) + ' KB');
}
main();
