from PIL import Image, ImageDraw

SCALE = 3
def new_canvas(w, h, bg=(0,0,0)):
    return Image.new('RGB', (w, h), bg)

def P(img, x, y, w, h, c):
    d = ImageDraw.Draw(img)
    d.rectangle([x, y, x+w-1, y+h-1], fill=c)

# ---------- pixel font (ported from the game) ----------
FONT = {
 'A':'.XX.|X..X|XXXX|X..X|X..X','B':'XXX.|X..X|XXX.|X..X|XXX.','C':'.XXX|X...|X...|X...|.XXX',
 'D':'XXX.|X..X|X..X|X..X|XXX.','E':'XXXX|X...|XXX.|X...|XXXX','F':'XXXX|X...|XXX.|X...|X...',
 'G':'.XXX|X...|X.XX|X..X|.XXX','H':'X..X|X..X|XXXX|X..X|X..X','I':'XXX|.X.|.X.|.X.|XXX',
 'J':'..XX|...X|...X|X..X|.XX.','K':'X..X|X.X.|XX..|X.X.|X..X','L':'X...|X...|X...|X...|XXXX',
 'M':'X...X|XX.XX|X.X.X|X...X|X...X','N':'X..X|XX.X|X.XX|X..X|X..X','O':'.XX.|X..X|X..X|X..X|.XX.',
 'P':'XXX.|X..X|XXX.|X...|X...','Q':'.XX.|X..X|X..X|X.XX|.XXX','R':'XXX.|X..X|XXX.|X.X.|X..X',
 'S':'.XXX|X...|.XX.|...X|XXX.','T':'XXX|.X.|.X.|.X.|.X.','U':'X..X|X..X|X..X|X..X|.XX.',
 'V':'X...X|X...X|.X.X.|.X.X.|..X..','W':'X...X|X...X|X.X.X|XX.XX|X...X',
 'X':'X..X|X..X|.XX.|X..X|X..X','Y':'X.X|X.X|.X.|.X.|.X.','Z':'XXXX|...X|.XX.|X...|XXXX',
 '0':'.XX.|X..X|X..X|X..X|.XX.','1':'.X.|XX.|.X.|.X.|XXX','2':'XX.|..X|.X.|X..|XXX',
 '3':'XX.|..X|.X.|..X|XX.','4':'X.X|X.X|XXX|..X|..X','5':'XXX|X..|XX.|..X|XX.',
 '6':'.XX|X..|XXX|X.X|XXX','7':'XXX|..X|.X.|.X.|.X.','8':'XXX|X.X|XXX|X.X|XXX',
 '9':'XXX|X.X|XXX|..X|XX.',
 '.':'.|.|.|.|X',',':'..|..|..|.X|X.','!':'X|X|X|.|X','?':'XX.|..X|.X.|...|.X.',
 "'":'X|X|.|.|.','-':'...|...|XXX|...|...',':':'.|X|.|X|.','/':'..X|.X.|.X.|.X.|X..'
}
def draw_text(img, s, x, y, c, scale=1):
    cx = x
    for ch in s.upper():
        if ch == ' ':
            cx += 3*scale; continue
        g = FONT.get(ch)
        if not g:
            cx += 4*scale; continue
        rows = g.split('|')
        for r, row in enumerate(rows):
            for q, cell in enumerate(row):
                if cell == 'X':
                    P(img, cx+q*scale, y+r*scale, scale, scale, c)
        cx += (len(rows[0])+1)*scale
    return cx - x
def text_w(s, scale=1):
    w = 0
    for ch in s.upper():
        if ch == ' ': w += 3*scale; continue
        g = FONT.get(ch)
        w += (len(g.split('|')[0])+1)*scale if g else 4*scale
    return w

# ---------- sprite drawing from string art ----------
def draw_sprite(img, art, legend, x, y, scale=1):
    rows = [r for r in art.strip('\n').split('\n')]
    for r, row in enumerate(rows):
        for q, ch in enumerate(row):
            if ch == '.' or ch == ' ':
                continue
            c = legend.get(ch)
            if c:
                P(img, x+q*scale, y+r*scale, scale, scale, c)

# ---------- shared colors ----------
K  = (24, 24, 32)      # outline
SK = (244, 200, 152)   # skin
SD = (206, 152, 106)   # skin shade
WH = (245, 245, 250)   # white
NV = (58, 56, 66)      # samuel black coat
NS = (40, 38, 48)      # black coat shade
RD = (198, 58, 70)     # red accent
HT = (44, 48, 60)      # hat
HB = (154, 44, 60)     # hat band crimson
MC = (66, 42, 26)      # mustache brown
GD = (226, 178, 62)    # gold
GY = (150, 150, 160)   # gray
BR = (56, 54, 62)      # herschel black coat
BS = (38, 36, 44)      # brown shade
BE = (222, 222, 230)   # beard silver
TE = (52, 156, 142)    # rosalind teal
TS = (34, 112, 102)    # teal shade
AU = (168, 84, 44)     # auburn hair
RY = (60, 58, 68)      # william black coat
RS = (42, 40, 50)     # royal shade
GH = (50, 50, 62)      # william black hair
GS = (32, 32, 42)
BL = (226, 194, 108)   # samuel blonde
BF = (172, 172, 184)   # herschel beard shade
AR = (208, 172, 92)    # roman armor gold
AS = (168, 130, 58)
RC = (170, 52, 52)     # roman cape red
LF = (110, 168, 74)    # laurel green
BZ = (196, 148, 70)    # brass
BD = (150, 106, 44)    # brass dark

# ---------- SAMUEL front battle sprite (26 wide) ----------
SAMUEL_F = """
......KKKKKKKKKKKK......
.....KHHHHHHHHHHHHK.....
.....KHHHHHHHHHHHHK.....
.....KHHHHHHHHHHHHK.....
.....KHHHHHHHHHHHHK.....
.....KBBBBBBBBBBBBK.....
...KKKKKKKKKKKKKKKKKK...
...KHHHHHHHHHHHHHHHHK...
...KKKKKKKKKKKKKKKKKK...
.....KYYYYYYYYYYYYK.....
....KYSSSSSSSSSSSSYK....
....KYSKKSSSSSSKKSYK....
....KYSKKSSSSSSKKSYK....
....KYSSSSSSSSSSSSYK....
....KYDKMMMKKMMMKDYK....
.....KSKMMMKKMMMKSK.....
.....KSSSKKKKKKSSSK.....
......KSSSSSSSSSSK......
......KKSSSSSSSSKK......
....KKNNKKKKKKKKNNKK....
...KNNNNNKWWWWKNNNNNK...
..KNNNNNNKWRRWKNNNNNNK..
..KNSSNNNKWWWWKNNNSSNK..
..KNSSNNNKWWWWKNNNSSNK..
..KNNNNNNKWWWWKNNNNNNK..
..KKNNNNNKWGGWKNNNNNKK..
...KKKNNNKWWWWKNNNKKK...
.....KNNNKKKKKKNNNK.....
.....KKKKKKKKKKKKKK.....
"""
SAMUEL_LEG = {'K':K,'H':HT,'B':HB,'S':SK,'D':SD,'M':MC,'N':NV,'W':WH,'R':RD,'G':GD,'Y':BL}
# 'S' inside suit rows means navy shade
SAMUEL_LEG2 = dict(SAMUEL_LEG)

def samuel_front(img, x, y, scale=1):
    # patch: suit shading uses 'S' char collision with skin; draw in two passes
    art = SAMUEL_F
    rows = art.strip('\n').split('\n')
    for r, row in enumerate(rows):
        for q, ch in enumerate(row):
            if ch in '. ':
                continue
            c = SAMUEL_LEG.get(ch, K)
            if ch == 'S' and r >= 19:   # suit region: shade navy
                c = NS
            P(img, x+q*scale, y+r*scale, scale, scale, c)

# ---------- SAMUEL back sprite (for battle, 30 wide, chunky) ----------
SAMUEL_B = """
.......KKKKKKKKKKKKKK.......
......KHHHHHHHHHHHHHHK......
......KHHHHHHHHHHHHHHK......
......KHHHHHHHHHHHHHHK......
......KHHHHHHHHHHHHHHK......
......KHHHHHHHHHHHHHHK......
....KKKKKKKKKKKKKKKKKKKK....
....KHHHHHHHHHHHHHHHHHHK....
....KKKKKKKKKKKKKKKKKKKK....
.......KYYYYYYYYYYYYK.......
.......KYYYYYYYYYYYYK.......
......KKKYYSSSSSSYYKKK......
....KKNNNKKKKKKKKKKNNNKK....
...KNNNNNNNNNNNNNNNNNNNNK...
..KNNNNNNNNNNNNNNNNNNNNNNK..
..KNNNNNNNNNNNNNNNNNNNNNNK..
..KNVVNNNNNNNNNNNNNNNNVVNK..
..KNVVNNNNNNNNNNNNNNNNVVNK..
..KNNNNNNNNNNNNNNNNNNNNNNK..
..KKNNNNNNNNNNNNNNNNNNNNKK..
...KKKKKKKKKKKKKKKKKKKKKK...
"""
def samuel_back(img, x, y, scale=1):
    draw_sprite(img, SAMUEL_B, {'K':K,'H':HT,'S':SK,'N':NV,'V':NS,'Y':BL}, x, y, scale)

# ---------- MC MAXIMVS front (32 wide, imposing) ----------
MAXIMVS = """
........LLK......KLL........
.......LLLLKKKKKKLLLL.......
......KKLLKHHHHHHKLLKK......
.......KKKHHHHHHHHKKK.......
........KSSSSSSSSSSK........
.......KSSSSSSSSSSSSK.......
.......KSKKSSSSSSKKSK.......
.......KSKKSSSSSSKKSK.......
.......KSSSSSSSSSSSSK.......
.......KSDSSSKKSSSDSK.......
........KSSKKKKKKSSK........
........KKSSSSSSSSKK........
......KKAAKKKKKKKKAAKK......
....KKAAAAAAAAAAAAAAAAKK....
...KCAAAAAKAAAAAAKAAAAACK...
..KCCAAAAAKAAAAAAKAAAAACCK..
..KCCAAGAAKAAAAAAKAAGAACCK..
..KCCAAAAAKAAAAAAKAAAAACCK..
..KCCKAAAAKKKKKKKKAAAAKCCK..
..KCCKSSKAAAAAAAAAAKSSKCCK..
..KCCKSSKAAAAAAAAAAKSSKCCK..
..KCKKKKKAAAAAAAAAAKKKKKCK..
..KCK...KKAAKKKKAAKK...KCK..
..KKK....KAAK..KAAK....KKK..
.........KKKK..KKKK.........
"""
def maximvs_front(img, x, y, scale=1):
    draw_sprite(img, MAXIMVS, {'K':K,'L':LF,'H':HT,'S':SK,'D':SD,'A':AR,'G':AS,'C':RC}, x, y, scale)

# ---------- HERSCHEL front (26 wide, hunched, beard, cane) ----------
HERSCHEL = """
.....KKKKKKKKKKKK.......
....KHHHHHHHHHHHHK......
....KHHHHHHHHHHHHK......
....KBBBBBBBBBBBBK......
..KKKKKKKKKKKKKKKKKK....
..KHHHHHHHHHHHHHHHHK....
..KKKKKKKKKKKKKKKKKK....
....KSSSSSSSSSSSSK......
...KSSKKKSSSSKKKSSK.....
...KSEKKSSSSSSKKESK.....
...KSEESSSSSSSSEESK.....
...KEEEEEEEEEEEEEEK.....
...KEEEEEEKKEEEEEEK.....
...KEEEEEEEEEEEEEEK..K..
....KEEFFEEEEEEFFEK.KGK.
....KKFFFFFFFFFFFKK.KGK.
...KKRRKKKKKKKKRRKK.KGK.
..KRRRRRRRRRRRRRRRRKKGK.
..KRRRRRRRRRRRRRRRRKKGK.
..KRBBRRRRRRRRRRBBRK.GK.
..KRBBRRRRRRRRRRBBRKKGK.
..KRRRRRRRRRRRRRRRRK.GK.
..KKRRRRRRRRRRRRRRKK.GK.
...KKKKKKKKKKKKKKKK..KK.
"""
def herschel_front(img, x, y, scale=1):
    draw_sprite(img, HERSCHEL, {'K':K,'H':HT,'B':HB,'S':SK,'E':BE,'F':BF,'R':BR,'G':BD}, x, y, scale)

# ---------- WILLIAM front (26 wide, flowing hair, medal) ----------
WILLIAM = """
......KKKKKKKKKKKK......
.....KHHHHHHHHHHHHK.....
.....KHHHHHHHHHHHHK.....
.....KBBBBBBBBBBBBK.....
...KKKKKKKKKKKKKKKKKK...
...KHHHHHHHHHHHHHHHHK...
...KKKKKKKKKKKKKKKKKK...
..KGGKSSSSSSSSSSSSKGGK..
..KGGKSSSSSSSSSSSSKGGK..
.KGGGKOKKOOOOOOKKOKGGGK.
.KGGGKSOOSSSSSSOOSKGGGK.
.KGGGKSSSSSSSSSSSSKGGGK.
.KGSGKSSDSSSSSSDSSKGSGK.
.KGSGKSSSKKKKKKSSSKGSGK.
.KGGGKSSSKWWWWKSSSKGGGK.
.KGGGKKSSSKKKKSSSKKGGGK.
..KGGKKKSSSSSSSSKKKGGK..
..KKGGKKKKKKKKKKKKGGKK..
...KKYYYKWWWWWWKYYYKK...
...KYYYYKWWWWWWKYYYYK...
..KYYYYYYKWMMWKYYYYYYK..
..KYSSYYYKWWWWKYYYSSYK..
..KYSSYYYKWWWWKYYYSSYK..
..KYYYYYYKWWWWKYYYYYYK..
..KKYYYYYKWWWWKYYYYYKK..
...KKKKKKKKKKKKKKKKKK...
"""
def william_front(img, x, y, scale=1):
    rows = WILLIAM.strip('\n').split('\n')
    leg = {'K':K,'H':HT,'B':HB,'S':SK,'D':SD,'G':GH,'W':WH,'Y':RY,'M':GD,'O':GD}
    for r, row in enumerate(rows):
        for q, ch in enumerate(row):
            if ch in '. ': continue
            c = leg.get(ch, K)
            if ch == 'S' and r >= 18: c = RS      # coat shading
            if ch == 'S' and r in (12,) and q in (2,3,20,21): c = GS
            P(img, x+q*scale, y+r*scale, scale, scale, c)

# ---------- ROSALIND front (26 wide, goggles on hat, buns, teal coat) ----------
ROSALIND = """
......KKKKKKKKKKKK......
.....KHHHHHHHHHHHHK.....
.....KGGGGGGGGGGGGK.....
.....KGBBGGGGGGBBGK.....
.....KGBBGGGGGGBBGK.....
.....KHHHHHHHHHHHHK.....
...KKKKKKKKKKKKKKKKKK...
...KHHHHHHHHHHHHHHHHK...
...KKKKKKKKKKKKKKKKKK...
..KAAKSSSSSSSSSSSSKAAK..
..KAAKSSSSSSSSSSSSKAAK..
..KAAKOKKOOOOOOKKOKAAK..
..KAAKSOOSSSSSSOOSKAAK..
..KKKKSSSSSSSSSSSSKKKK..
.....KSSDSSSSSSDSSK.....
.....KSSSKKKKKKSSSK.....
......KSSSSSSSSSSK......
......KKSSSSSSSSKK......
....KKTTKKKKKKKKTTKK....
...KTTTTTKWWWWKTTTTTK...
..KTTTTTTKWWWWKTTTTTTK..
..KTSSTTTKWWWWKTTTSSTK..
..KTSSTTTKWGGWKTTTSSTK..
..KTTTTTTKWWWWKTTTTTTK..
..KKTTTTTKWWWWKTTTTTKK..
...KKKKKKKKKKKKKKKKKK...
"""
def rosalind_front(img, x, y, scale=1):
    rows = ROSALIND.strip('\n').split('\n')
    leg = {'K':K,'H':HT,'G':BZ,'B':(170,220,235),'S':SK,'D':SD,'A':AU,'T':TE,'W':WH,'O':GD}
    for r, row in enumerate(rows):
        for q, ch in enumerate(row):
            if ch in '. ': continue
            c = leg.get(ch, K)
            if ch == 'S' and r >= 18: c = TS
            if ch == 'G' and r >= 18: c = GD
            P(img, x+q*scale, y+r*scale, scale, scale, c)

# ---------- 16x16 overworld walk sprites ----------
SAMUEL_WALK = """
....KKKKKKKK....
...KHHHHHHHHK...
...KHHHHHHHHK...
..KKKKKKKKKKKK..
...KYYYYYYYYK...
...KYKSSSSKYK...
...KSSSSSSSSK...
...KSKMMMMKSK...
....KKKKKKKK....
..KKNNKWWKNNKK..
..KNNNKWWKNNNK..
..KNNNKWWKNNNK..
...KNNNNNNNNK...
...KNKKKKKKNK...
...KNK....KNK...
...KKK....KKK...
"""
def samuel_walk(img, x, y, scale=1):
    draw_sprite(img, SAMUEL_WALK, {'K':K,'H':HT,'S':SK,'M':MC,'N':NV,'W':WH,'Y':BL}, x, y, scale)

BABBAGE_WALK = """
.....KKKKKK.....
....KZZZZZZK....
...KZZZZZZZZK...
...KZKKZZKKZK...
...KZKWZZKWZK...
...KZZZZZZZZK...
...KZZKKKKZZK...
....KZZZZZZK....
..KKKKKKKKKKKK..
..KZKZZZZZZKZK..
..KZKZDDDDZKZK..
..KKKZDZZDZKKK..
....KZZZZZZK....
....KZKKKKZK....
....KZK..KZK....
....KKK..KKK....
"""
def babbage_walk(img, x, y, scale=1):
    draw_sprite(img, BABBAGE_WALK, {'K':K,'Z':BZ,'D':BD,'W':WH}, x, y, scale)

print("sprites module loaded OK")
